<?xml version='1.0' encoding='utf-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>lxm-framework</artifactId>
    <packaging>pom</packaging>
    <version>2.0.0-java25-SNAPSHOT</version>
    <modules>
        <module>lxm-framework-parent</module>
        <module>lxm-framework-common</module>
        <module>lxm-framework-email</module>
        <module>lxm-framework-excel</module>
        <module>lxm-framework-mongo</module>
        <module>lxm-framework-mybatisplus</module>
        <module>lxm-framework-redis</module>
        <module>lxm-framework-web</module>
        <module>lxm-framework-all</module>
        <module>lxm-framework-auth</module>
        <module>lxm-framework-enigma</module>
    </modules>
    <parent>
        <artifactId>lxm-framework-parent</artifactId>
        <groupId>com.lxm</groupId>
        <version>2.0.0-java25-SNAPSHOT</version>
        <relativePath>lxm-framework-parent/pom.xml</relativePath>
    </parent>
</project>
